### ISSUE TITLE
Co dalej z grupą symfony-docs-pl?

### ISSUE THREAD

**Issue by abutronik** [symfony-docs-pl/ideas#9]
Panowie!

Praca nad naszym projektem zupełnie siadła. Kto z Was jest za kontunuacja projektu i jaką widzi role dla siebie?  Pozdrawiam @abutronik.

**Comment by chrisbujok** [comment]
Moim zdaniem, zważywszy na powszechną znajomość języka angielskiego (zwłaszcza wśród programistów), oryginalna wersja dokumentacji jest zupełnie wystarczająca, zatem osobiście nie widzę sensu kontynuacji projektu.
Jednocześnie dziękuję wszystkim za możliwość współtworzenia polskiego tłumaczenia te kilka lat temu :)
